# Change these first
owner: hayloftlabs # Your GitHub organization or username, where this repository lives
repo: hayloft-website-upptime # The name of this repository

sites:
  - name: Hayloft Advisors Website
    url: https://hayloftadvisors.com
  - name: Hayloft Chatbot
    url: $SECRET_SITE_HAYLOFT_N8N_CHATBOT
  - name: Hayloft n8n Prod
    url: $SECRET_SITE_HAYLOFT_N8N_PROD_SERVER
  - name: Hayloft n8n Dev
    url: $SECRET_SITE_HAYLOFT_N8N_DEV_SERVER
  - name: LPPRSWW, PLLC
    url: https://lpprsww.com
  - name: GCR public instance 01
    url: $SECRET_SITE_GOOGLE_RUN_PUBLIC_1
  - name: GCR public instance 02
    url: $SECRET_SITE_GOOGLE_RUN_PUBLIC_2
  - name: Hayloft n8n GCE 01
    url: $SECRET_SITE_GOOGLE_COMPUTE_N8N_01
  - name: Hayloft n8n GCE 02
    url: $SECRET_SITE_GOOGLE_COMPUTE_N8N_02

assignees:
  - lukewp

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: hayloftadvisors.com
  baseUrl: /hayloft-website-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Hayloft Advisors LLC
  theme: ocean
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: lukewp
